version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/expressProject
hooks:
  BeforeInstall:
    - location: scripts/clear_files
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root

